[tool.coverage.run]
source = [
  "custom_components",
]

[tool.coverage.report]
exclude_also = [
    "raise NotImplemented\\(\\)",
    "if __name__ == ['\"]__main__[\"']:",
]
show_missing = true

[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = [".git", ".mypy_cache", ".ruff_cache"]
addopts = [
    "-p syrupy",
    "--strict",
    "--cov=custom_components",
    "--cov-branch",
    "--cov-report=term",
    "--cov-report=html",
]

asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
required-version = ">=0.11.0"

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "I", # isort
]
ignore = [
  "E501",     # line too long
]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
voluptuous = "vol"
"homeassistant.helpers.config_validation" = "cv"
"homeassistant.helpers.device_registry" = "dr"
"homeassistant.helpers.entity_registry" = "er"
"homeassistant.helpers.issue_registry" = "ir"
"homeassistant.util.dt" = "dt_util"

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = false


[tool.mypy]
python_version = "3.13"
follow_imports = "normal"
local_partial_types = true
strict_equality = true
no_implicit_optional = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
enable_error_code = ["ignore-without-code", "redundant-self", "truthy-iterable"]
disable_error_code = ["annotation-unchecked", "import-not-found", "import-untyped"]
extra_checks = false
check_untyped_defs = true
warn_return_any = true
warn_unreachable = true
explicit_package_bases = true
